### ISSUE TITLE
error: no such package

### ISSUE THREAD

**Issue by foxeverfox** [psko/meteor-arcmenu#1]
when adding to meteor raise an error : 

error: no such package

**Comment by pistou** [comment]
Sorry for the waiting, I was on vacations.
I'll check this ASAP !

**Comment by pistou** [comment]
@foxeverfox I tried myself and found no error.

Could you give me more info on what you did?

**Comment by pistou** [comment]
Ok I think I got it, I had a typo on the readme.

Make sur to add `pistou:arcmenu`
I'll update the readme.
